<a href="https://colab.research.google.com/github/vishnubanna/learningmachinelearning/blob/master/ConvolutionNetworkFromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
## fix for many layers
import numpy as np
import pandas as pd
from math import floor

def sigmoid(x):
    return 1/(1 + np.exp(x))

class Convolution():
    def __init__(self, neurons, filter_shape, stride, neurons_prev = 1, max_pool = True):
        # each neuron is one filter
        if neurons_prev:
            self.filter_shape = (neurons_prev, filter_shape, filter_shape)
        else:
            self.filter_shape = (filter_shape, filter_shape)
        self.prev = neurons_prev
        self.stride = stride
        self.neurons = neurons
        self.bias = []
        self.filters = []
        self.max_pool = max_pool
        #self.out_shape = floor((input.shape[0] - self.filter_shape[0])/self.stride) + 1
        #self.input = input
        for i in range(self.neurons):
            temp = np.random.normal(loc = 0.0, scale = 1.0, size = self.filter_shape)
            self.filters.append(temp)
            bias = np.zeros(1)
            self.bias.append(bias)
        pass
    
    def __call__(self, input):
        self.input = input
        self.shape = input.shape 
        self.out_shape = floor((input.shape[1] - self.filter_shape[1])/self.stride) + 1
        self.outputs = [] #np.empty((self.neurons, self.out_shape, self.out_shape), dtype=float)
        #self.out_shape = floor((input.shape[0] - self.filter_shape[0])/self.stride) + 1
        #temp_shape = floor((self.input.shape[0] - self.filter_shape[0])/self.stride) + 1
        for i, filter in enumerate(self.filters):
            filter = np.rot90(filter, k = 2)
            output = np.empty((self.out_shape, self.out_shape), dtype=float)
            for y in range(0, output.shape[1], self.stride):
                for x in range(0, output.shape[0], self.stride):
                    wx = np.multiply(filter, self.input[:, x:(x + filter.shape[1]), y:(y + filter.shape[1])])
                    wx = np.sum(wx)
                    output[x, y] = wx + np.sum(self.bias)
            #output = abs(output * (output > 0))
            output = sigmoid(output)
            self.outputs.append(output)
            #self.outputs[i] = output
        #self.outputs = np.array(self.outputs)
        if not self.max_pool: 
            self.outputs = np.array(self.outputs)
        #self.outputs = abs(self.outputs * (self.outputs > 0))
        pass
    
    def train(self, error):
        pass
    
class maxPool2d():
    def __init__(self, filter_shape, stride):
        self.filter_shape = (filter_shape, filter_shape)
        self.stride = stride
        pass

    def __call__(self, input):
        self.input = input
        self.shape = input[1].shape
        self.out_shape = floor((self.shape[1] - self.filter_shape[1])/self.stride) + 1
        self.outputs = []
        for value in self.input:
            output = np.empty((self.out_shape, self.out_shape), dtype=float)
            for y in range(0, output.shape[1], self.stride):
                for x in range(0, output.shape[0], self.stride):
                    output[x, y] = np.max(value[x:(x + self.filter_shape[0]), y:(y + self.filter_shape[0])])
            self.outputs.append(output)
        self.outputs = np.array(self.outputs)
        pass
    
    def train(self):
        
        pass
    

In [0]:
max = 100
i = np.random.randint(1, max, size = (1,7,7))/max
print(i)
c1 = Convolution(2, 3, 1, neurons_prev = 1, max_pool = False)
print(c1.filters)

[[[0.06 0.85 0.9  0.12 0.51 0.6  0.81]
  [0.2  0.77 0.9  0.4  0.2  0.9  0.77]
  [0.17 0.24 0.82 0.91 0.66 0.87 0.71]
  [0.81 0.75 0.86 0.41 0.95 0.76 0.05]
  [0.87 0.01 0.1  0.91 0.55 0.97 0.51]
  [0.57 0.82 0.25 0.64 0.97 0.19 0.06]
  [0.31 0.44 0.25 0.59 0.09 0.5  0.44]]]
[array([[[-0.35132486,  2.13902176, -0.89268566],
        [-0.19256944,  1.02264596, -0.15015221],
        [-1.53889908,  0.88360707, -0.90105441]]]), array([[[-0.91802756,  1.49071956,  1.31245774],
        [ 1.87189158,  0.02671503, -0.26517528],
        [ 0.42973204,  1.6438303 ,  0.3587686 ]]])]


In [0]:
c1(i)
print(c1.outputs)

[[[0.45432584 0.27919996 0.61385546 0.49172183 0.31496905]
  [0.44937269 0.24681891 0.69240108 0.4185144  0.15486843]
  [0.66375441 0.59705435 0.38250718 0.69674365 0.24482031]
  [0.54994851 0.75485095 0.63949459 0.19067362 0.5034804 ]
  [0.52990353 0.70927029 0.15327193 0.80366441 0.45145892]]

 [[0.03991974 0.0043057  0.02024612 0.05161577 0.03512201]
  [0.03609189 0.03504985 0.02741634 0.01272775 0.03774214]
  [0.19506155 0.01177472 0.0043185  0.02565545 0.00465912]
  [0.01078217 0.1068776  0.03083868 0.01015869 0.11232523]
  [0.10449812 0.06848642 0.06110151 0.04455441 0.00631207]]]


In [0]:
# print(c1.filters[0], '\n',i[:, 0:3, 0:3])
# tmp = np.rot90(c1.filters[0], 2)
# print(np.multiply(tmp , i[:, 0:3, 0:3]))

# print(sigmoid(np.sum(np.multiply(tmp , i[:, 0:3, 0:3]))))

In [0]:
# c = maxPool2d(2, 1)
# c(c1.outputs)
# print(c.outputs)

In [0]:
c2 = Convolution(3, 3 , 1, neurons_prev = 2, max_pool = False)

In [0]:
# print(c.outputs.shape)
# c2(c.outputs)

print(c1.outputs.shape)
c2(c1.outputs)


(2, 5, 5)


In [0]:
print(c2.filters[0])
print(c1.outputs[:, 0:3, 0:3])
# print(np.multiply(c2.filters[0] , c.outputs[:, 0:3, 0:3]))
# print(np.sum(np.multiply(c2.filters[0] , c.outputs[:, 0:3, 0:3])))


[[[ 1.18120574 -0.86366991 -0.45900436]
  [-1.83896993  1.26521156  0.34846701]
  [-1.20228339 -0.94003688 -0.32117202]]

 [[ 0.7411569   1.9925884  -0.89160102]
  [ 0.36395747 -1.84030783 -0.41521077]
  [-1.49931085 -0.29336238 -0.33102185]]]
[[[0.45432584 0.27919996 0.61385546]
  [0.44937269 0.24681891 0.69240108]
  [0.66375441 0.59705435 0.38250718]]

 [[0.03991974 0.0043057  0.02024612]
  [0.03609189 0.03504985 0.02741634]
  [0.19506155 0.01177472 0.0043185 ]]]


In [0]:
# print(c(c2.outputs))
print(c2.outputs.shape)

(3, 3, 3)


In [0]:
# i2 = np.random.randint(1, 5, size = (3,2))
# print(i2)
i2 = c2.outputs
print(i2)


[[[0.51415124 0.83255929 0.60404059]
  [0.76332826 0.45220607 0.89154683]
  [0.76254777 0.90700077 0.46964065]]

 [[0.84804601 0.88373052 0.9074311 ]
  [0.90518459 0.91295077 0.90610057]
  [0.94986926 0.88536551 0.82736918]]

 [[0.06382493 0.262414   0.16661213]
  [0.09915829 0.16752446 0.26349618]
  [0.13573925 0.1366564  0.20988322]]]


In [0]:
# #i2 = np.reshape(i2, i2.size)
# #i2 = i2.flatten()
# i3 = np.random.randint(1, 5, size = (3,i2.size))

# print(i2, '\n\n', i3)

# print(np.dot(i3, i2.T))

In [0]:
#MLP
class Dense():
    def __init__(self, neurons, input_shape):
        self.input_shape = input_shape
        self.neurons = neurons
        self.weights = np.random.randint(-5, 5, size = (self.neurons, self.input_shape))
        pass
    
    def __call__(self, input):
        input = np.reshape(input, input.size)
        self.activate = np.dot(self.weights, input.T)
        pass
        
    def activation(self):
        self.activate = self.activate/np.max(self.activate)
        #self.outputs = abs(self.activate * (self.activate > 0))
        
        self.outputs = sigmoid(self.activate)

        pass
    
    def train(self, error):
        pass
    


class Softmax():
    def __init__(self, input):
        #input = input/np.max(input)
        self.outputs = np.exp(input)/(np.sum(np.exp(input)))
        #self.outputs = np.nan_to_num(self.outputs)
    def __call__(self):
        return self.outputs
        

In [0]:
# work on training

In [0]:
#i2 = np.reshape(i2, i2.size)
i2 = i2.flatten()
d1 = Dense(15, i2.size)
d1(i2)
d1.activation()
print(d1.outputs)
d2 = Dense(3, d1.outputs.size)
d2(d1.outputs)
d2.activation()
print(d2.outputs)

o = Softmax(d2.outputs)

print(o())
print(np.argmax(o()))
#print(np.exp(d1.outputs.T[0])/(np.sum(np.exp(d1.outputs.T[0]))))

[0.62056411 0.79706226 0.26894142 0.73465172 0.6832854  0.27336999
 0.34868854 0.40965159 0.52344526 0.63792473 0.79491514 0.48136742
 0.34047624 0.29587011 0.71883743]
[2.45967602e-57 2.68941421e-01 4.30947194e-15]
[0.30224461 0.39551079 0.30224461]
1


In [0]:
import numpy as np
import pandas as pd
from math import floor

class Dense():
    def __init__(self, neurons, input_shape, final = False):
        self.input_shape = input_shape
        self.neurons = neurons
        self.final = final
        #self.weights = np.random.randint(-5, 5, size = (self.neurons, self.input_shape))
        self.weights = np.random.normal(0.0, pow(self.input_shape, -0.5) ,size = (self.neurons, self.input_shape))
        pass

    def __call__(self, input):
        self.input = np.reshape(input, (input.size, 1))
        #self.input = input.flatten()
        self.input = self.input
        self.activate = np.dot(self.weights, self.input)
        pass

    def activation(self):
        #self.activate = self.activate/np.max(self.activate)
        #self.outputs = abs(self.activate * (self.activate > 0))
        if not self.final:
            self.outputs = sigmoid(self.activate)
        else:
            self.outputs = self.activate
        #print(self.outputs.shape)
        pass

    def train(self, error, lr):
        error = np.reshape(error, (error.size, 1))
        self.enext = np.dot(self.weights.T, error)
        temp = error * self.outputs * (1 - self.outputs)
        self.dweights = -lr * np.multiply((error * self.outputs * (1 - self.outputs)), self.input.T)
        #print(self.dweights.T.shape, self.weights.shape)
        #self.dweights = np.reshape(self.dweights, (self.neurons, self.input_shape))
        #print(self.dweights, '\n', self.weights)
        self.weights = self.weights + self.dweights
        #self.enext.reshape()
        #print(self.enext)
        return np.sum(self.enext, axis = 1)

class Softmax():
    def __init__(self, input):
        #input = input/np.max(input)
        self.outputs = np.exp(input)/(np.sum(np.exp(input)))
        #self.outputs = np.nan_to_num(self.outputs)
    def __call__(self):
        return self.outputs

In [0]:
max = 100
size = 100
tests = []
targets =[]
for i in range(size):
    test = np.random.randint(1, max, size = (1,7,7))/max
    tests.append(test)
    #target = np.random.randint(0, 2, size = size)
    target = np.random.randint(0, 2, size = 1)
    #target = np.reshape(target, (target.size, 1)) 
    targets.append(target)
    

    
#rect = test.flatten()
print(rect.shape)
target = np.random.randint(0, 2, size = size)
print(tests[size - 1], targets[size - 1])
l1 = Dense(100, test.size)
l2 = Dense(50, l1.neurons)
l3 = Dense(10, l2.neurons)
f = Dense(1, l3.neurons)

target = np.reshape(target, (target.size, 1)) 

for j in range(1000):
    for i,test in enumerate(tests):
        l1(test)
        l1.activation()

        l2(l1.outputs)
        l2.activation()
        
        l3(l2.outputs)
        l3.activation()


        f(l3.outputs)
        f.activation()
        
        test = -np.log(1 + (1/f.outputs))
        tt = sigmoid(targets[i])

        error = (targets[i] - f.outputs)
        #error = (tt - f.outputs)
        #error = (tt - f.outputs)
        

        #print(f.outputs,'\n error:' ,err)

        nerror = f.train(error, 0.1)
        #nerror = np.reshape(nerror, (nerror.size, 1))
        nerror = l3.train(nerror, 0.1)
        nerror = l2.train(nerror, 0.1)
        l1.train(nerror, 0.1)
        
print(f.outputs,'\n errors:' , (error**2),'\n error:', np.average(error)**2)

(49,)
[[[0.64 0.68 0.32 0.86 0.97 0.95 0.81]
  [0.34 0.88 0.35 0.01 0.1  0.58 0.1 ]
  [0.82 0.22 0.32 0.75 0.3  0.08 0.91]
  [0.75 0.06 0.36 0.55 0.12 0.03 0.13]
  [0.72 0.34 0.12 0.7  0.05 0.54 0.22]
  [0.75 0.21 0.59 0.14 0.79 0.17 0.79]
  [0.4  0.74 0.54 0.23 0.6  0.53 0.23]]] [0]
[[0.4372218]] 
 errors: [[0.1911629]] 
 error: 0.19116290102167527


In [0]:

l1(test)
l1.activation()

l2(l1.outputs)
l2.activation()


f(l2.outputs)
f.activation()

error = (np.reshape(target, (target.size, 1)) - f.outputs)

print(f.outputs,'\n' ,error**2)

nerror = f.train(error, 1)
#nerror = np.reshape(nerror, (nerror.size, 1))
nerror = l2.train(nerror, 0.1)
l1.train(nerror, 1)